// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDjp1nMPcPEqqWzQgjjC0TxG5cSv8cwIno',
//     appId: '1:866045502977:web:e4a7c66882ed14f7528200',
//     messagingSenderId: '866045502977',
//     projectId: 'jconnect-eaafe',
//     authDomain: 'jconnect-eaafe.firebaseapp.com',
//     storageBucket: 'jconnect-eaafe.firebasestorage.app',
//     measurementId: 'G-G1WFF3TTZ0',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB5CgShg2PhO45fz8G9D3MV9dI4kA-bPRc',
//     appId: '1:866045502977:android:e9161dee06a7fe60528200',
//     messagingSenderId: '866045502977',
//     projectId: 'jconnect-eaafe',
//     storageBucket: 'jconnect-eaafe.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDezfdG8QDNLgcCzsaDH4OJ3IgCVWZ2nLk',
//     appId: '1:866045502977:ios:14c5430f34afadcb528200',
//     messagingSenderId: '866045502977',
//     projectId: 'jconnect-eaafe',
//     storageBucket: 'jconnect-eaafe.firebasestorage.app',
//     iosBundleId: 'com.jll.jconnectplus',
//   );

// }